@startuml component
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!theme C4_superhero from https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/themes

LAYOUT_LANDSCAPE()
LAYOUT_WITH_LEGEND()

title Componente Diagram - Dinheiros S/A - Onboarding - Cadastro

Boundary(banco,"Dinheiros S/A") {
    Container(app_mobile, "Onboarding APP", "TypeScript, React Native", "App do banco")
    Container(app, "Onboarding Site", "JavaScript, Angular", "Sistema para gerenciamento e Onboarding via web browser")

    Boundary(aprovacao_boundary, "Fluxo De Cadastro"){
        Component(controller, "Cadastro Controller", "ASP NET Controller", "Ponto de entreada para onboarding")
        Component(criptografia, "Componente de Criptografia", "", "Responsável por anonimizar os dados cadastrados")
        Component(analise, "Componente de Analise de documento", "", "Valida os documentos enviados")

        Component(controller_aprovacao, "Aprovação Controller", "ASP NET Controller", "Ponto de entreada para aprovação do onboarding")
        Component(aprovacao, "Componente de aprovação", "", "Controla o fluxo de aprovação")
        Component(notificacao, "Componente de notificacao", "", "Notificar a aprovação do onboarding")
        ComponentDb(mongodb, "Database", "MongoDB", "Armazena os dados das contas")
    }
    
    ComponentQueue(queue_conta, "Onboarding finalizado", "Queue - RabbitMQ", "Mensagem de onboarding finalizado")
    Component_Ext(api_conta, "Conta API", "ASP NET 7", "Sistema de  gerenciamento de conta bancária")
}
Component_Ext(documentos, "Documento OCR API", "", "Analisa e retorna dados das imagens dos documentos enviado")

Rel(app, controller, "Faz chamadas para API", "HTTPS/JSON")
Rel(app, controller_aprovacao, "Faz chamadas para API", "HTTPS/JSON")
Rel(app_mobile, controller, "Faz chamadas para API", "HTTPS/JSON")

Rel(controller, analise, "Usa", "")
Rel(analise, criptografia, "Usa", "")
Rel(analise, mongodb, "Armazena dados no", "")
Rel(analise, documentos, "Valida documentos com", "")

Rel(controller_aprovacao, aprovacao, "Usa", "")
Rel(aprovacao, analise, "Usa", "")
Rel(aprovacao, queue_conta, "Enfileira aprovação no", "TCP/JSON")
Rel(queue_conta, api_conta, "Recebe mensagem de onbaording aprovado", "TCP/JSON")
